language: java
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

stages:
  - name: Building
  - name: Testing
  - name: Deployement

jobs:
  include:
    - stage: Building
      before_script:
        - chmod +x ./gradlew  # Ensure gradlew is executable
      script:
        - ./gradlew clean compileJava

    - stage: Testing
      before_script:
        - chmod +x ./gradlew  # Ensure gradlew is executable .
      script:
        - ./gradlew test
      after_failure:
        - echo "Tests failed. Check the test results for details."
      after_success:
        - echo "Tests passed successfully."
    
    - stage: Deployement
      script:
        - java -jar ./build/libs/hello-world-java-V1.jar

notifications:
  email:
    recipients:
      # - leon.karjunn@gmail.com
    on_success: always
    on_failure: always
